name: login_1
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4

  # Add other dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: '#f7f6f1'
  color_dark: '#272727'
  image: assets/images/worker.png
  image_dark: assets/images/worker.png

flutter:
  assets:
    - assets/images/worker.png
    - assets/images/plumber.png

